//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatchery
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCycle
    {
        public ProductionCycle()
        {
            this.DailyMonitoringPostLarvaLengkaps = new HashSet<DailyMonitoringPostLarvaLengkap>();
            this.Harvests = new HashSet<Harvest>();
        }
    
        public int ProductionCycleID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> Nauplii { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<bool> isInProduction { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<DailyMonitoringPostLarvaLengkap> DailyMonitoringPostLarvaLengkaps { get; set; }
        public virtual MasterModule MasterModule { get; set; }
        public virtual ICollection<Harvest> Harvests { get; set; }
    }
}
