//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatchery
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterParameterPostLarva
    {
        public int WaterParameterID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ProductionCycleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Alkalinty { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> NH3 { get; set; }
        public Nullable<double> Salinity { get; set; }
        public Nullable<double> DO { get; set; }
        public string Remark { get; set; }
        public string userID { get; set; }
        public string Algae { get; set; }
    }
}
