//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatchery
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroodStockMonitoring
    {
        public int BSMID { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<int> DeadMale { get; set; }
        public Nullable<int> DeadFemale { get; set; }
        public Nullable<double> Salinity { get; set; }
        public Nullable<double> MatTemp { get; set; }
        public Nullable<double> HatcTemp { get; set; }
        public Nullable<double> DO { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> PolychaeteIn { get; set; }
        public Nullable<double> PolychaeteUsed { get; set; }
        public Nullable<double> PolychaeteBalance { get; set; }
        public Nullable<double> SquidIn { get; set; }
        public Nullable<double> SquidUsed { get; set; }
        public Nullable<double> SquidiBalance { get; set; }
        public Nullable<double> FR { get; set; }
        public Nullable<double> EDTA { get; set; }
        public Nullable<double> Formaldehyde { get; set; }
        public Nullable<double> Treflan { get; set; }
        public Nullable<double> Iodine { get; set; }
        public Nullable<double> Vitamin { get; set; }
        public Nullable<int> Matured { get; set; }
        public Nullable<int> Mated { get; set; }
        public Nullable<int> Spawned { get; set; }
        public Nullable<double> Egg { get; set; }
        public Nullable<double> NaupliiBruto { get; set; }
        public Nullable<double> NaupliiNetto { get; set; }
        public Nullable<double> Flush { get; set; }
        public string Distribution { get; set; }
        public string Remark { get; set; }
        public string userID { get; set; }
    }
}
