//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatchery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMonitoringPostLarva
    {
        public int PostLarvaID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ProductionCycleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DOC { get; set; }
        public string Stage { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<double> BiosZ { get; set; }
        public Nullable<double> BiosM { get; set; }
        public Nullable<double> Bios100 { get; set; }
        public Nullable<double> Bios150 { get; set; }
        public Nullable<double> LanzyPL { get; set; }
        public Nullable<double> LanzyMPL { get; set; }
        public Nullable<double> LanzyZM { get; set; }
        public Nullable<double> MPZ { get; set; }
        public Nullable<double> MP1 { get; set; }
        public Nullable<double> MP2 { get; set; }
        public Nullable<double> MP3 { get; set; }
        public Nullable<double> MPL { get; set; }
        public Nullable<double> Spirulina { get; set; }
        public Nullable<double> LHF { get; set; }
        public Nullable<double> RoySF100_200 { get; set; }
        public Nullable<double> RoySF200_300 { get; set; }
        public Nullable<double> TzuFeng { get; set; }
        public Nullable<double> Artemia { get; set; }
        public Nullable<double> ArtemiaEZ1 { get; set; }
        public Nullable<double> ArtemiaEZ2 { get; set; }
        public Nullable<double> Activity { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> STDEV { get; set; }
        public Nullable<double> FGC { get; set; }
        public Nullable<double> Necrosis { get; set; }
        public Nullable<double> Fouling { get; set; }
        public Nullable<double> Parasite { get; set; }
        public Nullable<double> MGR { get; set; }
        public Nullable<double> Treflan { get; set; }
        public Nullable<double> Probiotik { get; set; }
        public string Remark { get; set; }
        public string userID { get; set; }
    }
}
