//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatchery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harvest
    {
        public int HarvestID { get; set; }
        public Nullable<int> ProductionCycleID { get; set; }
        public Nullable<int> DOC { get; set; }
        public string Stage { get; set; }
        public Nullable<int> HarvestedPopulation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string userid { get; set; }
    
        public virtual ProductionCycle ProductionCycle { get; set; }
    }
}
